% bicycle model 
% Written 01/12/26 Abigail Tucker

% all of this could really be tucked into one "getbicyclemmodel" function
% that can be called to any time spread determined manually in assmadif.
% Only meant to be accurate for steady state in generally linear region of
% tires. Should not need to be run live on car, dump lookup table into
% simulink 

% FOR FUTURE USERS: you need to update vehicle data spreadsheet, steering
% ratio (hidden in function below).Youll need to clear my 4 circles and
% adapt to whatever your chosen data set consists of (this is where one
% funciton would be way easier). 

% Could be expanded to double track,, tucked into one function, better
% filtering and interpolation methods, lots of other stuff.Cant decide if
% interpolated real steering ang or a simulated sweep makes more sense. 

clc
clear
close all


addpath vehicle_data ;
githubFolder = '\vehicle_data\';
parameterSpreadsheet = strcat(githubFolder,'zr25_data.xlsx');
ZR25 = vehicle(parameterSpreadsheet);
m = ZR25.mass_total;        % kg
a = ZR25.a;       % m
b = ZR25.b;       % 
L = ZR25.wheelbase ;
Iz = ZR25.yaw_polar_inertia; %kg * m^2,
TWFront = ZR25.track_width_front; % m
TWRear = ZR25.track_width_rear; % m
WheelRadius = ZR25.tire_loaded_radius ; % m


img = imread('SillyGoose.png');

f = figure( ...
    'Units','normalized', ...
    'OuterPosition',[0 0 1 1], ...
    'MenuBar','none', ...
    'ToolBar','none', ...
    'NumberTitle','off', ...
    'Color','k');

ax = axes(f, 'Position',[0 0 1 1]);
imshow(img, 'Parent',ax);
axis(ax,'off');

img = imread('ChatGPT Image Apr 12, 2026, 12_08_24 AM.png');

f = figure( ...
    'Units','normalized', ...
    'OuterPosition',[0 0 1 1], ...
    'MenuBar','none', ...
    'ToolBar','none', ...
    'NumberTitle','off', ...
    'Color','k');

ax = axes(f, 'Position',[0 0 1 1]);
imshow(img, 'Parent',ax);
axis(ax,'off');
img = imread('SillyGoose.png');

f = figure( ...
    'Units','normalized', ...
    'OuterPosition',[0 0 1 1], ...
    'MenuBar','none', ...
    'ToolBar','none', ...
    'NumberTitle','off', ...
    'Color','k');

ax = axes(f, 'Position',[0 0 1 1]);
imshow(img, 'Parent',ax);
axis(ax,'off');
img = imread('SillyGoose.png');

f = figure( ...
    'Units','normalized', ...
    'OuterPosition',[0 0 1 1], ...
    'MenuBar','none', ...
    'ToolBar','none', ...
    'NumberTitle','off', ...
    'Color','k');

ax = axes(f, 'Position',[0 0 1 1]);
imshow(img, 'Parent',ax);
axis(ax,'off');
img = imread('ChatGPT Image Apr 12, 2026, 12_08_24 AM.png');

f = figure( ...
    'Units','normalized', ...
    'OuterPosition',[0 0 1 1], ...
    'MenuBar','none', ...
    'ToolBar','none', ...
    'NumberTitle','off', ...
    'Color','k');

ax = axes(f, 'Position',[0 0 1 1]);
imshow(img, 'Parent',ax);
axis(ax,'off');
img = imread('SillyGoose.png');

f = figure( ...
    'Units','normalized', ...
    'OuterPosition',[0 0 1 1], ...
    'MenuBar','none', ...
    'ToolBar','none', ...
    'NumberTitle','off', ...
    'Color','k');

ax = axes(f, 'Position',[0 0 1 1]);
imshow(img, 'Parent',ax);
axis(ax,'off');

img = imread('ChatGPT Image Apr 12, 2026, 12_08_24 AM.png');

f = figure( ...
    'Units','normalized', ...
    'OuterPosition',[0 0 1 1], ...
    'MenuBar','none', ...
    'ToolBar','none', ...
    'NumberTitle','off', ...
    'Color','k');

ax = axes(f, 'Position',[0 0 1 1]);
imshow(img, 'Parent',ax);
axis(ax,'off');

img = imread('SillyGoose.png');

f = figure( ...
    'Units','normalized', ...
    'OuterPosition',[0 0 1 1], ...
    'MenuBar','none', ...
    'ToolBar','none', ...
    'NumberTitle','off', ...
    'Color','k');

ax = axes(f, 'Position',[0 0 1 1]);
imshow(img, 'Parent',ax);
axis(ax,'off');