% Produced by CVXGEN, 2025-03-31 14:19:24 -0400.
% CVXGEN is Copyright (C) 2006-2017 Jacob Mattingley, jem@cvxgen.com.
% The code in this file is Copyright (C) 2006-2017 Jacob Mattingley.
% CVXGEN, or solvers produced by CVXGEN, cannot be used for commercial
% applications without prior written permission from Jacob Mattingley.

% Filename: cvxsolve.m.
% Description: Solution file, via cvx, for use with sample.m.
function [vars, status] = cvxsolve(params, settings)
A = params.A;
P = params.P;
l = params.l;
q = params.q;
u = params.u;
cvx_begin
  % Caution: automatically generated by cvxgen. May be incorrect.
  variable x(4, 1);

  minimize((1/2)*quad_form(x, P) + q'*x);
  subject to
    l <= A*x;
    A*x <= u;
cvx_end
vars.x = x;
status.cvx_status = cvx_status;
% Provide a drop-in replacement for csolve.
status.optval = cvx_optval;
status.converged = strcmp(cvx_status, 'Solved');
