/* Generated C code for computing QP matrices
   Free parameters: Fx_fl_0, Fx_fr_0, Fx_rl_0, Fx_rr_0, Fy_fl_0, Fy_fr_0, Fy_rl_0, Fy_rr_0, Mz_tv, R, alpha_1, alpha_2, alpha_3, ax_ref, dFx_fl_ds, dFx_fr_ds, dFx_rl_ds, dFx_rr_ds, dFy_fl_ds, dFy_fr_ds, dFy_rl_ds, dFy_rr_ds, delta_fl, delta_fr, delta_rr, lf, lr, mass, s_fl_0, s_fr_0, s_rl_0, s_rr_0, tf, tr, w1, w2, w3
   Outputs: P (matrix) and q (vector) stored in arrays
*/
#include <math.h>

void computeQP(double Fx_fl_0, double Fx_fr_0, double Fx_rl_0, double Fx_rr_0, double Fy_fl_0, double Fy_fr_0, double Fy_rl_0, double Fy_rr_0, double Mz_tv, double R, double alpha_1, double alpha_2, double alpha_3, double ax_ref, double dFx_fl_ds, double dFx_fr_ds, double dFx_rl_ds, double dFx_rr_ds, double dFy_fl_ds, double dFy_fr_ds, double dFy_rl_ds, double dFy_rr_ds, double delta_fl, double delta_fr, double delta_rr, double lf, double lr, double mass, double s_fl_0, double s_fr_0, double s_rl_0, double s_rr_0, double tf, double tr, double w1, double w2, double w3, double* P, double* q) {
  /* Compute P matrix elements */
  P[0] = (1.0/(R*R)*1.0/(dFx_fl_ds*dFx_fl_ds)*w3*2.0)/alpha_3+(1.0/(R*R)*1.0/(dFx_fl_ds*dFx_fl_ds)*w1*pow(dFx_fl_ds*lf*sin(delta_fl)*2.0+dFy_fl_ds*tf*sin(delta_fl)+dFy_fl_ds*lf*cos(delta_fl)*2.0-dFx_fl_ds*tf*cos(delta_fl),2.0))/(alpha_1*2.0)+(1.0/(R*R)*1.0/(dFx_fl_ds*dFx_fl_ds)*1.0/(mass*mass)*w2*pow(dFx_fl_ds*cos(delta_fl)-dFy_fl_ds*sin(delta_fl),2.0)*2.0)/alpha_2;
  P[1] = (1.0/(R*R)*w1*(dFx_fl_ds*lf*sin(delta_fl)*2.0+dFy_fl_ds*tf*sin(delta_fl)+dFy_fl_ds*lf*cos(delta_fl)*2.0-dFx_fl_ds*tf*cos(delta_fl))*(dFx_fr_ds*lf*sin(delta_fr)*2.0-dFy_fr_ds*tf*sin(delta_fr)+dFy_fr_ds*lf*cos(delta_fr)*2.0+dFx_fr_ds*tf*cos(delta_fr)))/(alpha_1*dFx_fl_ds*dFx_fr_ds*2.0)+(1.0/(R*R)*1.0/(mass*mass)*w2*(dFx_fl_ds*cos(delta_fl)-dFy_fl_ds*sin(delta_fl))*(dFx_fr_ds*cos(delta_fr)-dFy_fr_ds*sin(delta_fr))*2.0)/(alpha_2*dFx_fl_ds*dFx_fr_ds);
  P[2] = (1.0/(R*R)*w1*(dFx_fl_ds*lf*sin(delta_fl)*2.0+dFy_fl_ds*tf*sin(delta_fl)+dFy_fl_ds*lf*cos(delta_fl)*2.0-dFx_fl_ds*tf*cos(delta_fl))*(dFx_rl_ds*lr*sin(delta_rr)*2.0-dFy_rl_ds*tr*sin(delta_rr)+dFy_rl_ds*lr*cos(delta_rr)*2.0+dFx_rl_ds*tr*cos(delta_rr))*(-1.0/2.0))/(alpha_1*dFx_fl_ds*dFx_rl_ds)+(1.0/(R*R)*1.0/(mass*mass)*w2*(dFx_fl_ds*cos(delta_fl)-dFy_fl_ds*sin(delta_fl))*(dFx_rl_ds*cos(delta_rr)-dFy_rl_ds*sin(delta_rr))*2.0)/(alpha_2*dFx_fl_ds*dFx_rl_ds);
  P[3] = (1.0/(R*R)*w1*(dFx_fl_ds*lf*sin(delta_fl)*2.0+dFy_fl_ds*tf*sin(delta_fl)+dFy_fl_ds*lf*cos(delta_fl)*2.0-dFx_fl_ds*tf*cos(delta_fl))*(dFx_rr_ds*lr*sin(delta_rr)*2.0+dFy_rr_ds*tr*sin(delta_rr)+dFy_rr_ds*lr*cos(delta_rr)*2.0-dFx_rr_ds*tr*cos(delta_rr))*(-1.0/2.0))/(alpha_1*dFx_fl_ds*dFx_rr_ds)+(1.0/(R*R)*1.0/(mass*mass)*w2*(dFx_fl_ds*cos(delta_fl)-dFy_fl_ds*sin(delta_fl))*(dFx_rr_ds*cos(delta_rr)-dFy_rr_ds*sin(delta_rr))*2.0)/(alpha_2*dFx_fl_ds*dFx_rr_ds);
  P[4] = (1.0/(R*R)*w1*(dFx_fl_ds*lf*sin(delta_fl)*2.0+dFy_fl_ds*tf*sin(delta_fl)+dFy_fl_ds*lf*cos(delta_fl)*2.0-dFx_fl_ds*tf*cos(delta_fl))*(dFx_fr_ds*lf*sin(delta_fr)*2.0-dFy_fr_ds*tf*sin(delta_fr)+dFy_fr_ds*lf*cos(delta_fr)*2.0+dFx_fr_ds*tf*cos(delta_fr)))/(alpha_1*dFx_fl_ds*dFx_fr_ds*2.0)+(1.0/(R*R)*1.0/(mass*mass)*w2*(dFx_fl_ds*cos(delta_fl)-dFy_fl_ds*sin(delta_fl))*(dFx_fr_ds*cos(delta_fr)-dFy_fr_ds*sin(delta_fr))*2.0)/(alpha_2*dFx_fl_ds*dFx_fr_ds);
  P[5] = (1.0/(R*R)*1.0/(dFx_fr_ds*dFx_fr_ds)*w3*2.0)/alpha_3+(1.0/(R*R)*1.0/(dFx_fr_ds*dFx_fr_ds)*w1*pow(dFx_fr_ds*lf*sin(delta_fr)*2.0-dFy_fr_ds*tf*sin(delta_fr)+dFy_fr_ds*lf*cos(delta_fr)*2.0+dFx_fr_ds*tf*cos(delta_fr),2.0))/(alpha_1*2.0)+(1.0/(R*R)*1.0/(dFx_fr_ds*dFx_fr_ds)*1.0/(mass*mass)*w2*pow(dFx_fr_ds*cos(delta_fr)-dFy_fr_ds*sin(delta_fr),2.0)*2.0)/alpha_2;
  P[6] = (1.0/(R*R)*w1*(dFx_fr_ds*lf*sin(delta_fr)*2.0-dFy_fr_ds*tf*sin(delta_fr)+dFy_fr_ds*lf*cos(delta_fr)*2.0+dFx_fr_ds*tf*cos(delta_fr))*(dFx_rl_ds*lr*sin(delta_rr)*2.0-dFy_rl_ds*tr*sin(delta_rr)+dFy_rl_ds*lr*cos(delta_rr)*2.0+dFx_rl_ds*tr*cos(delta_rr))*(-1.0/2.0))/(alpha_1*dFx_fr_ds*dFx_rl_ds)+(1.0/(R*R)*1.0/(mass*mass)*w2*(dFx_fr_ds*cos(delta_fr)-dFy_fr_ds*sin(delta_fr))*(dFx_rl_ds*cos(delta_rr)-dFy_rl_ds*sin(delta_rr))*2.0)/(alpha_2*dFx_fr_ds*dFx_rl_ds);
  P[7] = (1.0/(R*R)*w1*(dFx_fr_ds*lf*sin(delta_fr)*2.0-dFy_fr_ds*tf*sin(delta_fr)+dFy_fr_ds*lf*cos(delta_fr)*2.0+dFx_fr_ds*tf*cos(delta_fr))*(dFx_rr_ds*lr*sin(delta_rr)*2.0+dFy_rr_ds*tr*sin(delta_rr)+dFy_rr_ds*lr*cos(delta_rr)*2.0-dFx_rr_ds*tr*cos(delta_rr))*(-1.0/2.0))/(alpha_1*dFx_fr_ds*dFx_rr_ds)+(1.0/(R*R)*1.0/(mass*mass)*w2*(dFx_fr_ds*cos(delta_fr)-dFy_fr_ds*sin(delta_fr))*(dFx_rr_ds*cos(delta_rr)-dFy_rr_ds*sin(delta_rr))*2.0)/(alpha_2*dFx_fr_ds*dFx_rr_ds);
  P[8] = (1.0/(R*R)*w1*(dFx_fl_ds*lf*sin(delta_fl)*2.0+dFy_fl_ds*tf*sin(delta_fl)+dFy_fl_ds*lf*cos(delta_fl)*2.0-dFx_fl_ds*tf*cos(delta_fl))*(dFx_rl_ds*lr*sin(delta_rr)*2.0-dFy_rl_ds*tr*sin(delta_rr)+dFy_rl_ds*lr*cos(delta_rr)*2.0+dFx_rl_ds*tr*cos(delta_rr))*(-1.0/2.0))/(alpha_1*dFx_fl_ds*dFx_rl_ds)+(1.0/(R*R)*1.0/(mass*mass)*w2*(dFx_fl_ds*cos(delta_fl)-dFy_fl_ds*sin(delta_fl))*(dFx_rl_ds*cos(delta_rr)-dFy_rl_ds*sin(delta_rr))*2.0)/(alpha_2*dFx_fl_ds*dFx_rl_ds);
  P[9] = (1.0/(R*R)*w1*(dFx_fr_ds*lf*sin(delta_fr)*2.0-dFy_fr_ds*tf*sin(delta_fr)+dFy_fr_ds*lf*cos(delta_fr)*2.0+dFx_fr_ds*tf*cos(delta_fr))*(dFx_rl_ds*lr*sin(delta_rr)*2.0-dFy_rl_ds*tr*sin(delta_rr)+dFy_rl_ds*lr*cos(delta_rr)*2.0+dFx_rl_ds*tr*cos(delta_rr))*(-1.0/2.0))/(alpha_1*dFx_fr_ds*dFx_rl_ds)+(1.0/(R*R)*1.0/(mass*mass)*w2*(dFx_fr_ds*cos(delta_fr)-dFy_fr_ds*sin(delta_fr))*(dFx_rl_ds*cos(delta_rr)-dFy_rl_ds*sin(delta_rr))*2.0)/(alpha_2*dFx_fr_ds*dFx_rl_ds);
  P[10] = (1.0/(R*R)*1.0/(dFx_rl_ds*dFx_rl_ds)*w3*2.0)/alpha_3+(1.0/(R*R)*1.0/(dFx_rl_ds*dFx_rl_ds)*w1*pow(dFx_rl_ds*lr*sin(delta_rr)*2.0-dFy_rl_ds*tr*sin(delta_rr)+dFy_rl_ds*lr*cos(delta_rr)*2.0+dFx_rl_ds*tr*cos(delta_rr),2.0))/(alpha_1*2.0)+(1.0/(R*R)*1.0/(dFx_rl_ds*dFx_rl_ds)*1.0/(mass*mass)*w2*pow(dFx_rl_ds*cos(delta_rr)-dFy_rl_ds*sin(delta_rr),2.0)*2.0)/alpha_2;
  P[11] = (1.0/(R*R)*w1*(dFx_rl_ds*lr*sin(delta_rr)*2.0-dFy_rl_ds*tr*sin(delta_rr)+dFy_rl_ds*lr*cos(delta_rr)*2.0+dFx_rl_ds*tr*cos(delta_rr))*(dFx_rr_ds*lr*sin(delta_rr)*2.0+dFy_rr_ds*tr*sin(delta_rr)+dFy_rr_ds*lr*cos(delta_rr)*2.0-dFx_rr_ds*tr*cos(delta_rr)))/(alpha_1*dFx_rl_ds*dFx_rr_ds*2.0)+(1.0/(R*R)*1.0/(mass*mass)*w2*(dFx_rl_ds*cos(delta_rr)-dFy_rl_ds*sin(delta_rr))*(dFx_rr_ds*cos(delta_rr)-dFy_rr_ds*sin(delta_rr))*2.0)/(alpha_2*dFx_rl_ds*dFx_rr_ds);
  P[12] = (1.0/(R*R)*w1*(dFx_fl_ds*lf*sin(delta_fl)*2.0+dFy_fl_ds*tf*sin(delta_fl)+dFy_fl_ds*lf*cos(delta_fl)*2.0-dFx_fl_ds*tf*cos(delta_fl))*(dFx_rr_ds*lr*sin(delta_rr)*2.0+dFy_rr_ds*tr*sin(delta_rr)+dFy_rr_ds*lr*cos(delta_rr)*2.0-dFx_rr_ds*tr*cos(delta_rr))*(-1.0/2.0))/(alpha_1*dFx_fl_ds*dFx_rr_ds)+(1.0/(R*R)*1.0/(mass*mass)*w2*(dFx_fl_ds*cos(delta_fl)-dFy_fl_ds*sin(delta_fl))*(dFx_rr_ds*cos(delta_rr)-dFy_rr_ds*sin(delta_rr))*2.0)/(alpha_2*dFx_fl_ds*dFx_rr_ds);
  P[13] = (1.0/(R*R)*w1*(dFx_fr_ds*lf*sin(delta_fr)*2.0-dFy_fr_ds*tf*sin(delta_fr)+dFy_fr_ds*lf*cos(delta_fr)*2.0+dFx_fr_ds*tf*cos(delta_fr))*(dFx_rr_ds*lr*sin(delta_rr)*2.0+dFy_rr_ds*tr*sin(delta_rr)+dFy_rr_ds*lr*cos(delta_rr)*2.0-dFx_rr_ds*tr*cos(delta_rr))*(-1.0/2.0))/(alpha_1*dFx_fr_ds*dFx_rr_ds)+(1.0/(R*R)*1.0/(mass*mass)*w2*(dFx_fr_ds*cos(delta_fr)-dFy_fr_ds*sin(delta_fr))*(dFx_rr_ds*cos(delta_rr)-dFy_rr_ds*sin(delta_rr))*2.0)/(alpha_2*dFx_fr_ds*dFx_rr_ds);
  P[14] = (1.0/(R*R)*w1*(dFx_rl_ds*lr*sin(delta_rr)*2.0-dFy_rl_ds*tr*sin(delta_rr)+dFy_rl_ds*lr*cos(delta_rr)*2.0+dFx_rl_ds*tr*cos(delta_rr))*(dFx_rr_ds*lr*sin(delta_rr)*2.0+dFy_rr_ds*tr*sin(delta_rr)+dFy_rr_ds*lr*cos(delta_rr)*2.0-dFx_rr_ds*tr*cos(delta_rr)))/(alpha_1*dFx_rl_ds*dFx_rr_ds*2.0)+(1.0/(R*R)*1.0/(mass*mass)*w2*(dFx_rl_ds*cos(delta_rr)-dFy_rl_ds*sin(delta_rr))*(dFx_rr_ds*cos(delta_rr)-dFy_rr_ds*sin(delta_rr))*2.0)/(alpha_2*dFx_rl_ds*dFx_rr_ds);
  P[15] = (1.0/(R*R)*1.0/(dFx_rr_ds*dFx_rr_ds)*w3*2.0)/alpha_3+(1.0/(R*R)*1.0/(dFx_rr_ds*dFx_rr_ds)*w1*pow(dFx_rr_ds*lr*sin(delta_rr)*2.0+dFy_rr_ds*tr*sin(delta_rr)+dFy_rr_ds*lr*cos(delta_rr)*2.0-dFx_rr_ds*tr*cos(delta_rr),2.0))/(alpha_1*2.0)+(1.0/(R*R)*1.0/(dFx_rr_ds*dFx_rr_ds)*1.0/(mass*mass)*w2*pow(dFx_rr_ds*cos(delta_rr)-dFy_rr_ds*sin(delta_rr),2.0)*2.0)/alpha_2;
  /* Compute q vector elements */
  q[0] = (w1*(lf*(sin(delta_fl)/R+(dFy_fl_ds*cos(delta_fl))/(R*dFx_fl_ds))-(tf*(cos(delta_fl)/R-(dFy_fl_ds*sin(delta_fl))/(R*dFx_fl_ds)))/2.0)*(Mz_tv+lf*cos(delta_fl)*(Fy_fl_0-(Fx_fl_0*dFy_fl_ds)/dFx_fl_ds)+lf*cos(delta_fr)*(Fy_fr_0-(Fx_fr_0*dFy_fr_ds)/dFx_fr_ds)-lr*cos(delta_rr)*(Fy_rl_0-(Fx_rl_0*dFy_rl_ds)/dFx_rl_ds)-lr*cos(delta_rr)*(Fy_rr_0-(Fx_rr_0*dFy_rr_ds)/dFx_rr_ds)+(tf*sin(delta_fl)*(Fy_fl_0-(Fx_fl_0*dFy_fl_ds)/dFx_fl_ds))/2.0-(tf*sin(delta_fr)*(Fy_fr_0-(Fx_fr_0*dFy_fr_ds)/dFx_fr_ds))/2.0+(tr*sin(delta_rr)*(Fy_rl_0-(Fx_rl_0*dFy_rl_ds)/dFx_rl_ds))/2.0-(tr*sin(delta_rr)*(Fy_rr_0-(Fx_rr_0*dFy_rr_ds)/dFx_rr_ds))/2.0)*-2.0)/alpha_1-(w2*(cos(delta_fl)/R-(dFy_fl_ds*sin(delta_fl))/(R*dFx_fl_ds))*(ax_ref-(sin(delta_fl)*(Fy_fl_0-(Fx_fl_0*dFy_fl_ds)/dFx_fl_ds)+sin(delta_fr)*(Fy_fr_0-(Fx_fr_0*dFy_fr_ds)/dFx_fr_ds)+sin(delta_rr)*(Fy_rl_0-(Fx_rl_0*dFy_rl_ds)/dFx_rl_ds)+sin(delta_rr)*(Fy_rr_0-(Fx_rr_0*dFy_rr_ds)/dFx_rr_ds))/mass)*2.0)/(alpha_2*mass)-(1.0/(dFx_fl_ds*dFx_fl_ds)*w3*(Fx_fl_0-dFx_fl_ds*s_fl_0)*2.0)/(R*alpha_3);
  q[1] = (w1*(lf*(sin(delta_fr)/R+(dFy_fr_ds*cos(delta_fr))/(R*dFx_fr_ds))+(tf*(cos(delta_fr)/R-(dFy_fr_ds*sin(delta_fr))/(R*dFx_fr_ds)))/2.0)*(Mz_tv+lf*cos(delta_fl)*(Fy_fl_0-(Fx_fl_0*dFy_fl_ds)/dFx_fl_ds)+lf*cos(delta_fr)*(Fy_fr_0-(Fx_fr_0*dFy_fr_ds)/dFx_fr_ds)-lr*cos(delta_rr)*(Fy_rl_0-(Fx_rl_0*dFy_rl_ds)/dFx_rl_ds)-lr*cos(delta_rr)*(Fy_rr_0-(Fx_rr_0*dFy_rr_ds)/dFx_rr_ds)+(tf*sin(delta_fl)*(Fy_fl_0-(Fx_fl_0*dFy_fl_ds)/dFx_fl_ds))/2.0-(tf*sin(delta_fr)*(Fy_fr_0-(Fx_fr_0*dFy_fr_ds)/dFx_fr_ds))/2.0+(tr*sin(delta_rr)*(Fy_rl_0-(Fx_rl_0*dFy_rl_ds)/dFx_rl_ds))/2.0-(tr*sin(delta_rr)*(Fy_rr_0-(Fx_rr_0*dFy_rr_ds)/dFx_rr_ds))/2.0)*-2.0)/alpha_1-(w2*(cos(delta_fr)/R-(dFy_fr_ds*sin(delta_fr))/(R*dFx_fr_ds))*(ax_ref-(sin(delta_fl)*(Fy_fl_0-(Fx_fl_0*dFy_fl_ds)/dFx_fl_ds)+sin(delta_fr)*(Fy_fr_0-(Fx_fr_0*dFy_fr_ds)/dFx_fr_ds)+sin(delta_rr)*(Fy_rl_0-(Fx_rl_0*dFy_rl_ds)/dFx_rl_ds)+sin(delta_rr)*(Fy_rr_0-(Fx_rr_0*dFy_rr_ds)/dFx_rr_ds))/mass)*2.0)/(alpha_2*mass)-(1.0/(dFx_fr_ds*dFx_fr_ds)*w3*(Fx_fr_0-dFx_fr_ds*s_fr_0)*2.0)/(R*alpha_3);
  q[2] = (w1*(lr*(sin(delta_rr)/R+(dFy_rl_ds*cos(delta_rr))/(R*dFx_rl_ds))+(tr*(cos(delta_rr)/R-(dFy_rl_ds*sin(delta_rr))/(R*dFx_rl_ds)))/2.0)*(Mz_tv+lf*cos(delta_fl)*(Fy_fl_0-(Fx_fl_0*dFy_fl_ds)/dFx_fl_ds)+lf*cos(delta_fr)*(Fy_fr_0-(Fx_fr_0*dFy_fr_ds)/dFx_fr_ds)-lr*cos(delta_rr)*(Fy_rl_0-(Fx_rl_0*dFy_rl_ds)/dFx_rl_ds)-lr*cos(delta_rr)*(Fy_rr_0-(Fx_rr_0*dFy_rr_ds)/dFx_rr_ds)+(tf*sin(delta_fl)*(Fy_fl_0-(Fx_fl_0*dFy_fl_ds)/dFx_fl_ds))/2.0-(tf*sin(delta_fr)*(Fy_fr_0-(Fx_fr_0*dFy_fr_ds)/dFx_fr_ds))/2.0+(tr*sin(delta_rr)*(Fy_rl_0-(Fx_rl_0*dFy_rl_ds)/dFx_rl_ds))/2.0-(tr*sin(delta_rr)*(Fy_rr_0-(Fx_rr_0*dFy_rr_ds)/dFx_rr_ds))/2.0)*2.0)/alpha_1-(w2*(cos(delta_rr)/R-(dFy_rl_ds*sin(delta_rr))/(R*dFx_rl_ds))*(ax_ref-(sin(delta_fl)*(Fy_fl_0-(Fx_fl_0*dFy_fl_ds)/dFx_fl_ds)+sin(delta_fr)*(Fy_fr_0-(Fx_fr_0*dFy_fr_ds)/dFx_fr_ds)+sin(delta_rr)*(Fy_rl_0-(Fx_rl_0*dFy_rl_ds)/dFx_rl_ds)+sin(delta_rr)*(Fy_rr_0-(Fx_rr_0*dFy_rr_ds)/dFx_rr_ds))/mass)*2.0)/(alpha_2*mass)-(1.0/(dFx_rl_ds*dFx_rl_ds)*w3*(Fx_rl_0-dFx_rl_ds*s_rl_0)*2.0)/(R*alpha_3);
  q[3] = (w1*(lr*(sin(delta_rr)/R+(dFy_rr_ds*cos(delta_rr))/(R*dFx_rr_ds))-(tr*(cos(delta_rr)/R-(dFy_rr_ds*sin(delta_rr))/(R*dFx_rr_ds)))/2.0)*(Mz_tv+lf*cos(delta_fl)*(Fy_fl_0-(Fx_fl_0*dFy_fl_ds)/dFx_fl_ds)+lf*cos(delta_fr)*(Fy_fr_0-(Fx_fr_0*dFy_fr_ds)/dFx_fr_ds)-lr*cos(delta_rr)*(Fy_rl_0-(Fx_rl_0*dFy_rl_ds)/dFx_rl_ds)-lr*cos(delta_rr)*(Fy_rr_0-(Fx_rr_0*dFy_rr_ds)/dFx_rr_ds)+(tf*sin(delta_fl)*(Fy_fl_0-(Fx_fl_0*dFy_fl_ds)/dFx_fl_ds))/2.0-(tf*sin(delta_fr)*(Fy_fr_0-(Fx_fr_0*dFy_fr_ds)/dFx_fr_ds))/2.0+(tr*sin(delta_rr)*(Fy_rl_0-(Fx_rl_0*dFy_rl_ds)/dFx_rl_ds))/2.0-(tr*sin(delta_rr)*(Fy_rr_0-(Fx_rr_0*dFy_rr_ds)/dFx_rr_ds))/2.0)*2.0)/alpha_1-(w2*(cos(delta_rr)/R-(dFy_rr_ds*sin(delta_rr))/(R*dFx_rr_ds))*(ax_ref-(sin(delta_fl)*(Fy_fl_0-(Fx_fl_0*dFy_fl_ds)/dFx_fl_ds)+sin(delta_fr)*(Fy_fr_0-(Fx_fr_0*dFy_fr_ds)/dFx_fr_ds)+sin(delta_rr)*(Fy_rl_0-(Fx_rl_0*dFy_rl_ds)/dFx_rl_ds)+sin(delta_rr)*(Fy_rr_0-(Fx_rr_0*dFy_rr_ds)/dFx_rr_ds))/mass)*2.0)/(alpha_2*mass)-(1.0/(dFx_rr_ds*dFx_rr_ds)*w3*(Fx_rr_0-dFx_rr_ds*s_rr_0)*2.0)/(R*alpha_3);
}
